[package]
name = "xtuml-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.1", features = ["derive"] }
tera = "1.20.1"
anyhow = "1.0"
walkdir = "2.3"
include_dir = "0.7"